<?php

namespace StructureManager\Console\Commands;

use Carbon\Carbon;
use Illuminate\Console\Command;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\Log;
use Illuminate\Support\Facades\Schema;
use StructureManager\Handlers\StructureEventHandler;
use StructureManager\Services\FakeNotificationBuilder;
use StructureManager\Services\TestDataGenerator;
use Symfony\Component\Yaml\Yaml;

/**
 * Inject a fake CCP-shaped notification row into SeAT's
 * `character_notifications` table for end-to-end testing.
 *
 * Once injected, the row is indistinguishable from one SeAT pulled from
 * ESI on its 15-20 minute bucket. Within 60 seconds, SM's
 * `process-notifications` job picks it up, dedups against the local
 * `structure_manager_esi_notifications` table, calls
 * `StructureEventHandler::handle()` and dispatches the configured webhooks.
 *
 * SAFETY GATES (every guard has a fail-closed default):
 *
 *   1. structure_id MUST be in TestDataGenerator's safe ranges. Refuses to
 *      inject a notification "about" a real structure under any circumstances.
 *   2. character_id MUST be in TestDataGenerator's test character range.
 *      The character is auto-created via ensureTestCharacter if missing, so
 *      we never write to character_notifications without populating
 *      character_infos first (FK requirement).
 *   3. notification_id is generated by TestDataGenerator (8e18 range) so it
 *      cannot collide with real CCP notification IDs and is unmistakable
 *      to cleanup queries.
 *   4. timestamp is "now" by default — within SM's 2-hour processing window.
 *
 * Usage:
 *   php artisan structure-manager:inject-test-notification \
 *       --structure-id=2300000001 \
 *       --type=StructureUnderAttack \
 *       --attacker-corp="Test Aggressor"
 *
 *   php artisan structure-manager:inject-test-notification \
 *       --structure-id=2300000003 \
 *       --type=StructureLostShields \
 *       --time-left=86400
 */
class InjectTestNotificationCommand extends Command
{
    protected $signature = 'structure-manager:inject-test-notification
                            {--structure-id= : Target structure_id (must be a known test structure)}
                            {--type= : CCP notification type (e.g. StructureUnderAttack)}
                            {--character-id= : Recipient test character_id (default: derived from structure owner)}
                            {--attacker-character-id= : Override default attacker character_id (95000001)}
                            {--attacker-corp-id= : Override default attacker corp_id (98000001)}
                            {--attacker-corp= : Override default attacker corp name (Test Aggressor Corp)}
                            {--attacker-alliance-id= : Set attacker alliance_id (omit to skip alliance fields)}
                            {--attacker-alliance= : Set attacker alliance name (defaults to Test Alliance if -id is set)}
                            {--time-left= : Override timer duration in seconds (for reinforce / anchor / unanchor / sov reinforce)}
                            {--list : List supported notification types and exit}';

    protected $description = 'Inject a fake notification into character_notifications for end-to-end testing of SM dispatch.';

    public function handle(): int
    {
        if ($this->option('list')) {
            return $this->printSupportedTypes();
        }

        $structureId = (int) $this->option('structure-id');
        $type        = (string) $this->option('type');

        // ---- Gate 1: notification type must be supported
        if ($type === '') {
            $this->error('--type is required (use --list to see supported types).');
            return 1;
        }
        if (!isset(FakeNotificationBuilder::SUPPORTED_TYPES[$type])) {
            $this->error("Unknown notification type: {$type}");
            $this->line('Use --list to see supported types.');
            return 1;
        }

        // ---- Gate 2: structure_id must be in safe test range
        if ($structureId === 0) {
            $this->error('--structure-id is required.');
            return 1;
        }
        if (!TestDataGenerator::isTestStructure($structureId)) {
            $this->error(sprintf(
                'Refusing to inject: structure %d is NOT in the safe test range. ' .
                'Test structures live in %d..%d (or legacy IDs %d / %d). ' .
                'This guard exists so test injections cannot accidentally target real structures.',
                $structureId,
                TestDataGenerator::STRUCTURE_ID_MIN,
                TestDataGenerator::STRUCTURE_ID_MAX,
                TestDataGenerator::LEGACY_METENOX_ID,
                TestDataGenerator::LEGACY_ASTRAHUS_ID
            ));
            return 1;
        }

        // ---- Resolve owning corp (for the recipient character) from the structure row
        $structureRow = DB::table('corporation_structures')
            ->where('structure_id', $structureId)
            ->select('corporation_id')
            ->first();

        if ($structureRow === null) {
            $this->error("Structure #{$structureId} not found in corporation_structures. " .
                'Run `structure-manager:create-test-upwell-structures` first.');
            return 1;
        }

        $ownerCorpId = (int) $structureRow->corporation_id;

        // ---- Gate 3: recipient character must exist (or be createable in test range)
        $characterId = (int) ($this->option('character-id')
            ?? TestDataGenerator::primaryCharacterIdForCorp($ownerCorpId));

        if (!TestDataGenerator::isTestCharacter($characterId)) {
            $this->error(sprintf(
                'Refusing to inject: character %d is NOT in the safe test range. ' .
                'Test characters live in %d..%d.',
                $characterId,
                TestDataGenerator::CHARACTER_ID_MIN,
                TestDataGenerator::CHARACTER_ID_MAX
            ));
            return 1;
        }

        // Ensure the test character exists (idempotent — safe to call repeatedly)
        TestDataGenerator::ensureTestCharacter($characterId, $ownerCorpId);

        // ---- Build the YAML payload
        $params = $this->buildParamsFromOptions();

        try {
            $builder = new FakeNotificationBuilder();
            $built = $builder->build($type, $structureId, $params);
        } catch (\InvalidArgumentException $e) {
            $this->error('Build failed: ' . $e->getMessage());
            return 1;
        }

        // ---- Generate a safe-range notification_id and insert
        $notificationId = TestDataGenerator::nextNotificationId();
        $now = Carbon::now();

        // 1. Audit-trail row in character_notifications (so the test mirrors
        //    what a real CCP notification looks like in the SeAT table)
        DB::table('character_notifications')->insert([
            'character_id'    => $characterId,
            'notification_id' => $notificationId,
            'type'            => $built['type'],
            'sender_id'       => $built['sender_id'],
            'sender_type'     => $built['sender_type'],
            'timestamp'       => $now,
            'is_read'         => false,
            'text'            => $built['text'],
            'created_at'      => $now,
            'updated_at'      => $now,
        ]);

        // 2. Mark as already-dispatched in BOTH dedup tables (whichever exist)
        //    so neither SM's process-notifications fallback nor MC's sweep
        //    re-dispatches this later. This is what lets us safely call the
        //    handler synchronously below.
        $this->markDispatchedEverywhere(
            $notificationId, $characterId, $ownerCorpId, $built, $now
        );

        // 3. Synchronously dispatch via SM's StructureEventHandler.
        //
        //    Why synchronous: the polling pipeline can take 1-10 min
        //    depending on detection mode, MC presence, and cron cadence —
        //    too slow for an interactive test. Going direct gives ~instant
        //    feedback (the webhook usually fires within a second or two).
        //    Step 2 above prevents double-dispatch when polling later runs.
        //
        //    The notification_id is in TestDataGenerator's safe range so
        //    StructureEventHandler::dispatch() will route to the configured
        //    test_webhook_url (NOT production webhooks). See the dispatch
        //    hook for the safe-range check.
        try {
            $mockNotification = (object) [
                'notification_id' => $notificationId,
                'character_id'    => $characterId,
                'corporation_id'  => $ownerCorpId,
                'type'            => $built['type'],
                'sender_id'       => $built['sender_id'],
                'sender_type'     => $built['sender_type'],
                'timestamp'       => $now,
                'text'            => $built['text'],
                'parsed_data'     => Yaml::parse($built['text']),
                'source'          => 'test_inject',
            ];

            StructureEventHandler::handle($mockNotification);
            $this->info("✓ Injected + synchronously dispatched {$type}");
        } catch (\Throwable $e) {
            // Don't fail the whole command if dispatch hits an issue —
            // the audit row is already in place, polling will retry on
            // the next cycle if dedup wasn't latched.
            $this->warn("Notification injected but synchronous dispatch failed: " . $e->getMessage());
            Log::warning("InjectTestNotification: sync dispatch failed for #{$notificationId}: " . $e->getMessage());
        }

        $this->line("    notification_id: {$notificationId}");
        $this->line("    structure_id:    {$structureId}");
        $this->line("    character_id:    {$characterId}  (corp {$ownerCorpId})");
        $this->newLine();
        $this->info('If a test_webhook_url is configured, the embed should already be in Discord.');
        $this->info('The Structure Board got a row, EventBus published a structure.alert.* event.');
        $this->newLine();
        $this->comment('Cleanup: php artisan structure-manager:cleanup-test-data');

        return 0;
    }

    /**
     * Mark the notification as already-dispatched in both dedup tables so
     * the polling jobs skip it.
     *
     * SM's `structure_manager_esi_notifications` is always present.
     * MC's `manager_core_esi_notifications` is conditionally present
     * (only if MC is installed).
     */
    private function markDispatchedEverywhere(int $notificationId, int $characterId, int $corporationId, array $built, Carbon $now): void
    {
        // SM's dedup table — processed=true so SM's fallback skips
        try {
            $smRow = [
                'notification_id' => $notificationId,
                'character_id'    => $characterId,
                'corporation_id'  => $corporationId,
                'type'            => $built['type'],
                'sender_id'       => $built['sender_id'],
                'sender_type'     => $built['sender_type'],
                'timestamp'       => $now,
                'text'            => $built['text'],
                'parsed_data'     => json_encode(Yaml::parse($built['text'])),
                'source'          => 'test_inject',
                'processed'       => true,
                'processed_at'    => $now,
                'created_at'      => $now,
                'updated_at'      => $now,
            ];
            DB::table('structure_manager_esi_notifications')->insert($smRow);
        } catch (\Throwable $e) {
            Log::warning("InjectTestNotification: failed to write SM dedup latch for #{$notificationId}: " . $e->getMessage());
        }

        // MC's dedup table — dispatched=true so MC's sweep + poll skip
        if (Schema::hasTable('manager_core_esi_notifications')) {
            try {
                $mcRow = [
                    'notification_id' => $notificationId,
                    'character_id'    => $characterId,
                    'corporation_id'  => $corporationId,
                    'type'            => $built['type'],
                    'sender_id'       => $built['sender_id'],
                    'sender_type'     => $built['sender_type'],
                    'timestamp'       => $now,
                    'text'            => $built['text'],
                    'parsed_data'     => json_encode(Yaml::parse($built['text'])),
                    'source'          => 'test_inject',
                    'dispatched'      => true,
                    'dispatched_at'   => $now,
                    'created_at'      => $now,
                    'updated_at'      => $now,
                ];
                DB::table('manager_core_esi_notifications')->insert($mcRow);
            } catch (\Throwable $e) {
                // Schema differences between MC versions — try a minimal fallback
                Log::debug("InjectTestNotification: MC full row insert failed, trying minimal: " . $e->getMessage());
                try {
                    DB::table('manager_core_esi_notifications')->insert([
                        'notification_id' => $notificationId,
                        'character_id'    => $characterId,
                        'corporation_id'  => $corporationId,
                        'type'            => $built['type'],
                        'timestamp'       => $now,
                        'source'          => 'test_inject',
                        'dispatched'      => true,
                        'created_at'      => $now,
                        'updated_at'      => $now,
                    ]);
                } catch (\Throwable $e2) {
                    Log::warning("InjectTestNotification: failed to write MC dedup latch for #{$notificationId}: " . $e2->getMessage());
                }
            }
        }
    }

    /**
     * Translate CLI flags into FakeNotificationBuilder $params keys.
     */
    private function buildParamsFromOptions(): array
    {
        $params = [];

        $map = [
            'attacker-character-id' => 'attacker_character_id',
            'attacker-corp-id'      => 'attacker_corp_id',
            'attacker-corp'         => 'attacker_corp_name',
            'attacker-alliance-id'  => 'attacker_alliance_id',
            'attacker-alliance'     => 'attacker_alliance_name',
            'time-left'             => 'time_left_seconds',
        ];

        foreach ($map as $opt => $key) {
            $val = $this->option($opt);
            if ($val !== null && $val !== '') {
                $params[$key] = $val;
            }
        }

        return $params;
    }

    /**
     * Print a grouped list of supported types so admins know what to pass to --type.
     */
    private function printSupportedTypes(): int
    {
        $byFamily = [];
        foreach (FakeNotificationBuilder::SUPPORTED_TYPES as $type => $cfg) {
            $byFamily[$cfg['family']][] = $type . '  — ' . $cfg['label'];
        }

        $familyOrder = ['attack', 'lifecycle', 'fuel', 'services', 'sov'];
        foreach ($familyOrder as $family) {
            if (!isset($byFamily[$family])) continue;
            $this->info(strtoupper($family));
            foreach ($byFamily[$family] as $line) {
                $this->line('  ' . $line);
            }
            $this->newLine();
        }

        return 0;
    }
}
